"use client";

import { useEffect, useRef, useState } from "react";
import { ArrowDown, ArrowRight, ArrowUpRight, Download, Mail, Menu, X } from "lucide-react";

const work = [
  {n:"01",title:"Credit Card Fraud Detection",type:"Machine Learning · 1.85M transactions",image:"/images/project-fraud.png",copy:"An end-to-end classification study for highly imbalanced financial data—from exploratory analysis and preprocessing to model evaluation.",tech:"Python · Pandas · NumPy · Scikit-learn",steps:["Problem","EDA","Balance","Train","Evaluate"]},
  {n:"02",title:"Local Event Finder",type:"Full-stack data product",image:"/images/project-events.png",copy:"A location-aware discovery platform built as a real software product, with a FastAPI service layer and PostgreSQL data architecture.",tech:"FastAPI · PostgreSQL · REST API · Python",steps:["Discover","Filter","Rank","Map","Manage"]},
  {n:"03",title:"Web Security Assessment",type:"Application security",image:"/images/project-security.png",copy:"A structured security assessment that translates testing evidence into risk context and actionable remediation recommendations.",tech:"Docker · OWASP · Security Testing",steps:["Recon","Test","Find","Assess","Recommend"]},
];

function DataField(){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current;if(!c)return;const gl=c.getContext("webgl",{alpha:true});if(!gl)return;const vs=gl.createShader(gl.VERTEX_SHADER)!,fs=gl.createShader(gl.FRAGMENT_SHADER)!;gl.shaderSource(vs,"attribute vec2 p;void main(){gl_Position=vec4(p,0.,1.);}");gl.shaderSource(fs,"precision mediump float;uniform vec2 r;uniform vec2 m;uniform float t;void main(){vec2 uv=(gl_FragCoord.xy-.5*r)/r.y;vec2 mm=(m-.5*r)/r.y;float d=length(uv-mm*.18);float rings=.015/abs(sin(d*18.-t*.45)*.55+d*2.);float grid=step(.985,sin(uv.x*75.)*sin(uv.y*75.));vec3 col=vec3(.278,.545,1.)*(rings*.24+grid*.035);gl_FragColor=vec4(col,min(.5,rings*.16+grid*.03));}");gl.compileShader(vs);gl.compileShader(fs);const pr=gl.createProgram()!;gl.attachShader(pr,vs);gl.attachShader(pr,fs);gl.linkProgram(pr);gl.useProgram(pr);const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);const p=gl.getAttribLocation(pr,"p");gl.enableVertexAttribArray(p);gl.vertexAttribPointer(p,2,gl.FLOAT,false,0,0);const rr=gl.getUniformLocation(pr,"r"),mm=gl.getUniformLocation(pr,"m"),tt=gl.getUniformLocation(pr,"t");let mx=0,my=0,raf=0;const resize=()=>{const d=Math.min(devicePixelRatio,1.4);c.width=innerWidth*d;c.height=innerHeight*d;gl.viewport(0,0,c.width,c.height);mx=c.width*.6;my=c.height*.5};const move=(e:PointerEvent)=>{mx=e.clientX*Math.min(devicePixelRatio,1.4);my=(innerHeight-e.clientY)*Math.min(devicePixelRatio,1.4)};const draw=(now:number)=>{gl.uniform2f(rr,c.width,c.height);gl.uniform2f(mm,mx,my);gl.uniform1f(tt,now*.001);gl.drawArrays(gl.TRIANGLES,0,3);raf=requestAnimationFrame(draw)};resize();addEventListener("resize",resize);addEventListener("pointermove",move);raf=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(raf);removeEventListener("resize",resize);removeEventListener("pointermove",move)}},[]);return <canvas ref={ref} className="data-field" aria-hidden="true"/>}

export default function Home(){const[menu,setMenu]=useState(false);useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("show")),{threshold:.13});document.querySelectorAll(".motion").forEach(x=>o.observe(x));const onScroll=()=>document.documentElement.style.setProperty("--scroll",`${scrollY/(document.documentElement.scrollHeight-innerHeight)*100}%`);addEventListener("scroll",onScroll,{passive:true});return()=>{o.disconnect();removeEventListener("scroll",onScroll)}},[]);return <main>
  <DataField/><div className="progress"/><header><a className="logo" href="#home">MK<span>/</span>26</a><nav className={menu?"active":""}>{["Profile","Work","Experience","Freelance","Skills","Contact"].map(x=><a key={x} href={`#${x.toLowerCase()}`} onClick={()=>setMenu(false)}>{x}</a>)}<a className="cv" href="#contact">CV <Download size={13}/></a></nav><button onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?<X/>:<Menu/>}</button></header>

  <section className="new-hero" id="home"><div className="hero-visual"><img src="/images/identity-hero.png" alt="Abstract representation of an AI and data engineer at work"/><div className="visual-grid"/><span className="visual-code">SYSTEM / PROFILE_01</span><div className="visual-orbit"><i/><i/><i/></div></div><div className="hero-copy"><div className="availability motion"><i/> Germany · Available 01.12.2026</div><p className="micro motion">AI & DATA ANALYTICS / SOFTWARE DEVELOPMENT</p><h1>{["Mohan","Kumar."].map((x,i)=><span className="motion" style={{transitionDelay:`${i*.12}s`}} key={x}>{x}</span>)}</h1><p className="intro motion">I build intelligent, data-driven systems—combining practical software-development experience with machine learning and analytics.</p><div className="hero-buttons motion"><a className="btn blue" href="#work">Explore projects <ArrowDown size={16}/></a><a className="btn line" href="#contact">Let&apos;s connect <ArrowUpRight size={16}/></a></div></div><aside><span>01</span><p>Master&apos;s student<br/>MDH University<br/>Germany</p></aside></section>

  <section className="snapshot"><div><small>FOCUS</small><b>AI & Data Analytics</b></div><div><small>BACKGROUND</small><b>Software Development</b></div><div><small>SEEKING</small><b>Working Student Role</b></div><div><small>FOUNDER</small><b>Webinfine Solutions</b></div></section>

  <section className="story" id="profile"><div className="story-title motion"><span>02 / PROFILE</span><h2>Software thinking.<br/><em>Data intelligence.</em></h2><p>My path is not a reset—it is an expansion. I use the discipline of software engineering to build stronger analytical and machine-learning solutions.</p></div><div className="story-image motion"><img src="/images/identity-journey.png" alt="Code structures evolving into AI and data analytics"/><div className="story-points"><span>CODE</span><i/><span>DATA</span><i/><span>MODELS</span><i/><span>DEPLOY</span></div></div><div className="timeline motion"><Timeline year="2025" role="Software Intern" place="Simplify 3X · Bengaluru"/><Timeline year="2025/26" role="Web Developer" place="909 Infotech · Bengaluru"/><Timeline year="2026/27" role="M.S. Information Technology" place="AI & Data Analytics · MDH University" last/></div></section>

  <section className="selected" id="work"><div className="section-head motion"><span>03 / SELECTED WORK</span><h2>Technical case studies<br/>with real depth.</h2><p>Scroll through three projects spanning machine learning, data products and application security.</p></div>{work.map((w,i)=><article className="case motion" key={w.n}><div className="case-image"><img src={w.image} alt=""/><div className="case-scan"/><div className="case-index">{w.n}</div></div><div className="case-copy"><span>{w.type}</span><h3>{w.title}</h3><p>{w.copy}</p><b>{w.tech}</b><div className="case-steps">{w.steps.map((s,j)=><i key={s}><small>{j+1}</small>{s}</i>)}</div></div></article>)}</section>

  <section className="career" id="experience"><div className="section-head motion"><span>04 / EXPERIENCE</span><h2>Experience that<br/>ships.</h2></div><div className="career-grid"><Experience date="DEC 2025 — MAR 2026" role="Web Developer" company="909 Infotech Private Limited" list="Web applications · Frontend & backend · Database operations · Query optimisation · Testing"/><Experience date="JAN 2025 — JUN 2025" role="Software Intern" company="Simplify 3X Private Limited" list="Development support · Testing · Debugging · Database management · Documentation"/></div></section>

  <section className="webinfine" id="freelance">
    <div className="wf-top motion"><span>05 / MY FREELANCE COMPANY</span><a href="https://webinfine.com/" target="_blank" rel="noreferrer">Visit Webinfine Solutions <ArrowUpRight size={15}/></a></div>
    <div className="wf-hero"><div className="wf-title motion"><p>FOUNDED &amp; RUN BY MOHAN KUMAR</p><h2>Webinfine<br/><em>Solutions.</em></h2><p className="wf-lead">Webinfine Solutions is my own freelance company. I created it to work directly with clients while completing my master&apos;s studies—turning business requirements into websites, software, connected systems and automation.</p><div className="wf-identity"><div><small>MY ROLE</small><b>Founder · Freelance Developer</b></div><div><small>PURPOSE</small><b>Accept &amp; deliver paid client projects</b></div><div><small>STATUS</small><b>Operating alongside my studies</b></div><div><small>ENGAGEMENT</small><b>Available for freelance projects</b></div></div><a className="wf-visit" href="https://webinfine.com/" target="_blank" rel="noreferrer">Explore my company website <ArrowUpRight size={18}/></a></div><div className="wf-command motion"><div className="cmd-head"><b>WEBINFINE / SYSTEM MAP</b><i>ACTIVE</i></div><div className="cmd-core"><span>CLIENT</span><div><i/><i/><i/></div><strong>IDEA TO<br/>DELIVERY</strong></div><div className="cmd-nodes"><span>CRM</span><span>HRM</span><span>WEB</span><span>AI</span><span>AUTO</span></div><div className="cmd-foot"><span>DISCOVER</span><i/><span>BUILD</span><i/><span>LAUNCH</span><i/><span>GROW</span></div></div></div>
    <div className="wf-founder-note motion"><span>STUDY &amp; CAREER</span><p>It complements my studies and software-development background. I am also seeking a Working Student opportunity in Germany from 01 December 2026.</p></div>
    <div className="wf-services"><div className="wf-services-title motion"><span>WHAT WE BUILD</span><h3>One partner.<br/>Connected capability.</h3><p>Solutions are designed around the way teams, customers and operations actually work—not around disconnected tools.</p></div><div className="wf-service-grid">{[["01","Web & App Development","Responsive, performance-focused websites, web applications and customer portals built for real business use."],["02","CRM & Business Platforms","Connected CRM, HRM, ERP-style workflows, dashboards and custom operational software."],["03","AI & Automation","AI assistants, WhatsApp automation and workflows that reduce repetitive work and improve response speed."],["04","Commerce & Growth","E-commerce systems, integrations, SEO and digital foundations designed to support measurable growth."],["05","APIs & Integrations","Architecture that connects existing tools, data and services instead of creating another isolated system."],["06","Support & Evolution","Ongoing optimisation, monitoring, improvements and new features so products can scale without starting over."]].map(([n,t,c])=><article className="motion" key={n}><span>{n}</span><h4>{t}</h4><p>{c}</p><ArrowUpRight size={18}/></article>)}</div></div>
    <div className="wf-principles motion"><span>HOW WE DEVELOP</span><div><p><b>Workflow first.</b> We understand the real process before selecting the technology.</p><p><b>Integration by design.</b> APIs and system connections are planned early in the architecture.</p><p><b>Premium, practical UX.</b> Interfaces stay clear, fast and easy for real teams to use.</p><p><b>Built to evolve.</b> Modular systems can gain features and automation without being rebuilt.</p></div></div>
    <div className="wf-process"><div className="wf-process-head motion"><span>HOW WE WORK</span><h3>From business problem<br/>to working system.</h3></div><div className="wf-process-track">{[["01","Discover","Business, users and workflows"],["02","Architect","UX, system and technical plan"],["03","Engineer","Build, integrate and test"],["04","Launch","Deploy, optimise and monitor"],["05","Scale","Support, automate and improve"]].map(([n,t,c])=><article className="motion" key={n}><span>{n}</span><i/><h4>{t}</h4><p>{c}</p></article>)}</div></div>
    <div className="wf-cta motion"><div><span>WORK WITH MY FREELANCE COMPANY</span><h3>Have a project?<br/>Let&apos;s build it.</h3></div><a href="https://webinfine.com/" target="_blank" rel="noreferrer">Go to webinfine.com <ArrowUpRight size={20}/></a></div>
  </section>

  <section className="stack" id="skills"><div className="section-head motion"><span>06 / CAPABILITIES</span><h2>A connected<br/>technology stack.</h2></div><div className="stack-grid">{[["AI & DATA","Python · Pandas · NumPy · Scikit-learn · Machine Learning"],["BACKEND & DATA","FastAPI · REST APIs · SQL · PostgreSQL"],["DEVELOPMENT","JavaScript · HTML · CSS · Git · GitHub"],["CLOUD & DEVOPS","Docker · Azure"]].map(([a,b],i)=><article className="motion" key={a}><small>0{i+1}</small><h3>{a}</h3><p>{b}</p><div className="signal"><i/><i/><i/><i/></div></article>)}</div></section>

  <section className="degree"><span>07 / EDUCATION</span><div className="degree-main motion"><p>APR 2026</p><h2>MDH University<br/>of Applied Sciences</h2><p>20 AUG 2027</p></div><div className="degree-bottom"><b>M.S. Information Technology<br/><em>AI & Data Analytics</em></b><p>English — Fluent<br/>German — A1, learning<br/>Telugu — Native</p></div></section>

  <section className="end" id="contact"><p className="motion">OPEN TO WORKING STUDENT & FREELANCE OPPORTUNITIES</p><h2 className="motion">Let&apos;s turn data<br/>into <em>impact.</em></h2><div className="end-row motion"><span>Germany · Available December 2026</span><a className="btn dark" href="mailto:">Start a conversation <Mail size={16}/></a></div><footer><span>© 2026 MOHAN KUMAR</span><a href="#home">BACK TO TOP ↑</a></footer></section>
  </main>}

function Timeline({year,role,place,last}:{year:string,role:string,place:string,last?:boolean}){return <div><span>{year}</span><b>{role}</b><p>{place}</p>{!last&&<ArrowDown/>}</div>}
function Experience({date,role,company,list}:{date:string,role:string,company:string,list:string}){return <article className="motion"><span>{date}</span><h3>{role}</h3><b>{company}</b><p>{list}</p><ArrowRight/></article>}
